# list from https://www.textfixer.com/tutorials/common-english-words.txt (via Wikipedia)
STOP_WORDS = [
  'a', 'able', 'about', 'across', 'after', 'all', 'almost', 'also', 'am', 'among', 'an', 'and',
  'any', 'are', 'as', 'at', 'be', 'because', 'been', 'but', 'by', 'can', 'cannot', 'could', 'dear',
  'did', 'do', 'does', 'either', 'else', 'ever', 'every', 'for', 'from', 'get', 'got', 'had', 'has',
  'have', 'he', 'her', 'hers', 'him', 'his', 'how', 'however', 'i', 'if', 'in', 'into', 'is', 'it',
  'its', 'just', 'least', 'let', 'like', 'likely', 'may', 'me', 'might', 'most', 'must', 'my',
  'neither', 'no', 'nor', 'not', 'of', 'off', 'often', 'on', 'only', 'or', 'other', 'our', 'own',
  'rather', 'said', 'say', 'says', 'she', 'should', 'since', 'so', 'some', 'than', 'that', 'the',
  'their', 'them', 'then', 'there', 'these', 'they', 'this', 'tis', 'to', 'too', 'twas', 'us',
  'wants', 'was', 'we', 'were', 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why',
  'will', 'with', 'would', 'yet', 'you', 'your',
]

# list from https://www.link-assistant.com/seo-stop-words.html
SEO_STOP_WORDS = [
  'a', 'able', 'about', 'above', 'abroad', 'according', 'accordingly', 'across', 'actually',
  'adj', 'after', 'afterwards', 'again', 'against', 'ago', 'ahead', 'ain', 'all', 'allow',
  'allows', 'almost', 'alone', 'along', 'alongside', 'already', 'also', 'although', 'always',
  'am', 'amid', 'amidst', 'among', 'amongst', 'an', 'and', 'another', 'any', 'anybody', 'anyhow',
  'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'apart', 'appear', 'appreciate',
  'appropriate', 'are', 'aren', 'around', 'as', 'a', 'aside', 'ask', 'asking', 'associated',
  'at', 'available', 'away', 'awfully', 'b', 'back', 'backward', 'backwards', 'be', 'became',
  'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'begin', 'behind',
  'being', 'believe', 'below', 'beside', 'besides', 'best', 'better', 'between', 'beyond', 'both',
  'brief', 'but', 'by', 'c', 'came', 'can', 'cannot', 'cant', 'can', 'caption', 'cause', 'causes',
  'certain', 'certainly', 'changes', 'clearly', 'c', 'co', 'co', 'com', 'come', 'comes',
  'concerning', 'consequently', 'consider', 'considering', 'contain', 'containing', 'contains',
  'corresponding', 'could', 'couldn', 'course', 'c', 'currently', 'd', 'dare', 'daren',
  'definitely', 'described', 'despite', 'did', 'didn', 'different', 'directly', 'do', 'does',
  'doesn', 'doing', 'done', 'don', 'down', 'downwards', 'during', 'e', 'each', 'edu', 'eg',
  'eight', 'eighty', 'either', 'else', 'elsewhere', 'end', 'ending', 'enough', 'entirely',
  'especially', 'et', 'etc', 'even', 'ever', 'evermore', 'every', 'everybody', 'everyone',
  'everything', 'everywhere', 'ex', 'exactly', 'example', 'except', 'f', 'fairly', 'far',
  'farther', 'few', 'fewer', 'fifth', 'first', 'five', 'followed', 'following', 'follows',
  'for', 'forever', 'former', 'formerly', 'forth', 'forward', 'found', 'four', 'from', 'further',
  'furthermore', 'g', 'get', 'gets', 'getting', 'given', 'gives', 'go', 'goes', 'going', 'gone',
  'got', 'gotten', 'greetings', 'h', 'had', 'hadn', 'half', 'happens', 'hardly', 'has', 'hasn',
  'have', 'haven', 'having', 'he', 'he', 'he', 'hello', 'help', 'hence', 'her', 'here',
  'hereafter', 'hereby', 'herein', 'here', 'hereupon', 'hers', 'herself', 'he', 'hi', 'him',
  'himself', 'his', 'hither', 'hopefully', 'how', 'howbeit', 'however', 'hundred', 'i', 'i',
  'ie', 'if', 'ignored', 'i', 'i', 'immediate', 'in', 'inasmuch', 'inc', 'inc', 'indeed',
  'indicate', 'indicated', 'indicates', 'inner', 'inside', 'insofar', 'instead', 'into',
  'inward', 'is', 'isn', 'it', 'it', 'it', 'its', 'it', 'itself', 'i', 'j', 'just', 'k',
  'keep', 'keeps', 'kept', 'know', 'known', 'knows', 'l', 'last', 'lately', 'later', 'latter',
  'latterly', 'least', 'less', 'lest', 'let', 'let', 'like', 'liked', 'likely', 'likewise',
  'little', 'look', 'looking', 'looks', 'low', 'lower', 'ltd', 'm', 'made', 'mainly', 'make',
  'makes', 'many', 'may', 'maybe', 'mayn', 'me', 'mean', 'meantime', 'meanwhile', 'merely',
  'might', 'mightn', 'mine', 'minus', 'miss', 'more', 'moreover', 'most', 'mostly', 'mr', 'mrs',
  'much', 'must', 'mustn', 'my', 'myself', 'n', 'name', 'namely', 'nd', 'near', 'nearly',
  'necessary', 'need', 'needn', 'needs', 'neither', 'never', 'neverf', 'neverless',
  'nevertheless', 'new', 'next', 'nine', 'ninety', 'no', 'nobody', 'non', 'none',
  'nonetheless', 'noone', 'nor', 'normally', 'not', 'nothing', 'notwithstanding', 'novel', 'now',
  'nowhere', 'o', 'obviously', 'of', 'off', 'often', 'oh', 'ok', 'okay', 'old', 'on', 'once',
  'one', 'ones', 'one', 'only', 'onto', 'opposite', 'or', 'other', 'others', 'otherwise',
  'ought', 'oughtn', 'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'overall', 'own',
  'p', 'particular', 'particularly', 'past', 'per', 'perhaps', 'placed', 'please', 'plus',
  'possible', 'presumably', 'probably', 'provided', 'provides', 'q', 'que', 'quite', 'qv', 'r',
  'rather', 'rd', 're', 'really', 'reasonably', 'recent', 'recently', 'regarding', 'regardless',
  'regards', 'relatively', 'respectively', 'right', 'round', 's', 'said', 'same', 'saw', 'say',
  'saying', 'says', 'second', 'secondly', 'see', 'seeing', 'seem', 'seemed', 'seeming', 'seems',
  'seen', 'self', 'selves', 'sensible', 'sent', 'serious', 'seriously', 'seven', 'several',
  'shall', 'shan', 'she', 'she', 'she', 'she', 'should', 'shouldn', 'since', 'six', 'so', 'some',
  'somebody', 'someday', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhat',
  'somewhere', 'soon', 'sorry', 'specified', 'specify', 'specifying', 'still', 'sub', 'such',
  'sup', 'sure', 't', 'take', 'taken', 'taking', 'tell', 'tends', 'th', 'than', 'thank',
  'thanks', 'thanx', 'that', 'that', 'thats', 'that', 'that', 'the', 'their', 'theirs',
  'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'there', 'therefore',
  'therein', 'there', 'there', 'theres', 'there', 'thereupon', 'there', 'these', 'they', 'they',
  'they', 'they', 'they', 'thing', 'things', 'think', 'third', 'thirty', 'this', 'thorough',
  'thoroughly', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'till',
  'to', 'together', 'too', 'took', 'toward', 'towards', 'tried', 'tries', 'truly', 'try',
  'trying', 't', 'twice', 'two', 'u', 'un', 'under', 'underneath', 'undoing', 'unfortunately',
  'unless', 'unlike', 'unlikely', 'until', 'unto', 'up', 'upon', 'upwards', 'us', 'use',
  'used', 'useful', 'uses', 'using', 'usually', 'v', 'value', 'various', 'versus', 'very',
  'via', 'viz', 'vs', 'w', 'want', 'wants', 'was', 'wasn', 'way', 'we', 'we', 'welcome',
  'well', 'we', 'went', 'were', 'we', 'weren', 'we', 'what', 'whatever', 'what', 'what',
  'what', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein',
  'where', 'whereupon', 'wherever', 'whether', 'which', 'whichever', 'while', 'whilst',
  'whither', 'who', 'who', 'whoever', 'whole', 'who', 'whom', 'whomever', 'who', 'whose', 'why',
  'will', 'willing', 'wish', 'with', 'within', 'without', 'wonder', 'won', 'would', 'wouldn',
  'x', 'y', 'yes', 'yet', 'you', 'you', 'you', 'your', 'you', 'yours', 'yourself', 'yourselves',
  'you', 'z', 'zero',
]
